Add --profile to run Sidekick with profiling enabled
minio/sidekick pull request #71
Opened 2022-11-24 09:26 UTC by vadmeste

Exit the application or kill it to get profiling data saved in the 
current directory with a date timestamp.

2022-11-24 10:46 UTC, klauspost commented
@vadmeste I find the HTTP profilers to be much more useful since it doesn't require restarting. Maybe we could expose them on a separate port, so adding a parameter `--pprof=":6060"` would expose profiling on a separate port. 

> There is also a standard HTTP interface to profiling data. In an HTTP server, adding
> `import _ "net/http/pprof"` will install handlers for a few URLs under /debug/pprof/. Then you can run go tool pprof with a single argument—the URL to your server’s profiling data and it will download and examine a live profile.

```
go tool pprof http://localhost:6060/debug/pprof/profile   # 30-second CPU profile
go tool pprof http://localhost:6060/debug/pprof/heap      # heap profile
go tool pprof http://localhost:6060/debug/pprof/block     # goroutine blocking profile
```

- You will need to add the pprof to a custom mux, but there are easy functions for that. I can send a PR if you'd like.

2022-11-24 15:57 UTC, harshavardhana commented
> @vadmeste I find the HTTP profilers to be much more useful since it doesn't require restarting. Maybe we could expose them on a separate port, so adding a parameter `--pprof=":6060"` would expose profiling on a separate port.
> 
> > There is also a standard HTTP interface to profiling data. In an HTTP server, adding
> > `import _ "net/http/pprof"` will install handlers for a few URLs under /debug/pprof/. Then you can run go tool pprof with a single argument—the URL to your server’s profiling data and it will download and examine a live profile.
> 
> ```
> go tool pprof http://localhost:6060/debug/pprof/profile   # 30-second CPU profile
> go tool pprof http://localhost:6060/debug/pprof/heap      # heap profile
> go tool pprof http://localhost:6060/debug/pprof/block     # goroutine blocking profile
> ```
> 
> * You will need to add the pprof to a custom mux, but there are easy functions for that. I can send a PR if you'd like.

This is better as @klauspost suggested

2022-11-25 13:21 UTC, vadmeste commented
@klauspost I made the change, by the way, this does not require any flag.. it can be always enabled

2022-11-25 13:43 UTC, klauspost commented
@vadmeste The reason for the separate port is for safety reasons. While adding it to the default port is a lot easier, both for use and setup it does allow anyone to access potentially resource intensive calls.

2022-11-25 15:09 UTC, klauspost commented
Yes, why I wrote that "adding it to the default port is a lot easier, both for use and setup". But it doesn't look like something we would like to have exposed externally.

But it is easier to block a port.

2022-11-25 15:51 UTC, harshavardhana requested changes

2022-11-25 15:51 UTC, harshavardhana commented on main.go
> +	// TODO: replace /.prometheus with /minio/prometheus/metrics
This is chosen on purpose since there can never be buckets starting with a `.`  - so you can use `.pprof`

2022-11-26 08:30 UTC, harshavardhana requested changes

2022-11-26 08:30 UTC, harshavardhana commented on main.go
> +			Usage: "start and and listen on the specified address (e.g. `:6060`)",
```suggestion
			Usage: "start and listen for profiling on the specified address (e.g. `:1337`)",
```

2022-11-28 15:35 UTC, harshavardhana approved these changes

2022-11-28 15:37 UTC, merged